#!/bin/zsh

action=$(echo -e "Lock\nLogout\nSuspend\nReboot\nShutdown" | rofi -dmenu -theme ~/.config/rofi/.rofi.theme.powersettings -config ~/.config/rofi/.rofi.config -location 0)

case $action in
    Lock) betterlockscreen -l -- --greeter-text="" --keylayout 3;;
    Logout) killall i3 ;;
    Suspend) systemctl suspend ;;
    Reboot) systemctl reboot ;;
    Shutdown) systemctl poweroff -i ;;
esac
