#!/bin/zsh

action=$(echo -e "Screenshot (Fullscreen)\nScreenshot (Focused)" | rofi -theme-str 'inputbar { enabled: false;}' -dmenu -p "Screenshot:" -i -font "Terminus (TTF) 11" -hide-scrollbar -lines 2 -disable-history -width 15 -config ~/.rofi.rasi -no-click-to-exit)

case $action in
    "Screenshot (Fullscreen)") scrot -d 1 -e 'mv $f ~/Screenshots' ;;
    "Screenshot (Focused)") scrot -d 1 -ue 'mv $f ~/Screenshots' ;;
esac
