#!/bin/zsh

action=$(echo -e "Screenshot (Fullscreen)\nScreenshot (Focused)" | rofi -theme-str 'listview { lines: 2;} inputbar { enabled: false;}' -dmenu -theme ~/.config/rofi/.rofi.theme -config ~/.config/rofi/.rofi.config -location 0)

case $action in
    "Screenshot (Fullscreen)") scrot -d 1 -e 'mv $f ~/Screenshots' ;;
    "Screenshot (Focused)") scrot -d 1 -ue 'mv $f ~/Screenshots' ;;
esac
