#!/bin/bash

free=`cat /sys/class/drm/card0/device/mem_info_vis_vram_used`
total=`cat /sys/class/drm/card0/device/mem_info_vis_vram_total`
percent=$((200*$free/$total % 2 + 100*$free/$total))

echo $percent